main:
  catalog: 'demos'
  schema: 'subscriber_churn'
  volume: 'raw_data'

  tables:
    bronze:
      wikimedia_pageviews: 'bronze_wikimedia_pageviews'
      user_behavior: 'bronze_user_behavior'
      subscription_data: 'bronze_subscription_data'

    silver:
      user_features: 'silver_user_features'
      churn_features: 'silver_churn_features'

    gold:
      predictions: 'gold_churn_predictions'
      insights: 'gold_churn_insights'

  data_sources:
    wikimedia:
      base_url: 'https://dumps.wikimedia.org/other/pageviews/2025/2025-01'

  ml:
    experiment_name: 'churn_modeling_experiment'

  churn_config:
    churn_window_days: 90
    prediction_horizon_days: 30
    feature_lookback_days: 30
